export declare const STATUS_TEMPORARY = "TEMPORARY";
export declare const STATUS_TEMPORARY_ON_KEPT_BY_TTTS = "TEMPORARY_ON_KEPT_BY_TTTS";
export declare const STATUS_WAITING_SETTLEMENT = "WAITING_SETTLEMENT";
export declare const STATUS_WAITING_SETTLEMENT_PAY_DESIGN = "WAITING_SETTLEMENT_PAY_DESIGN";
export declare const STATUS_KEPT_BY_TTTS = "KEPT_BY_TTTS";
export declare const STATUS_KEPT_BY_MEMBER = "KEPT_BY_MEMBER";
export declare const STATUS_RESERVED = "RESERVED";
export declare const PURCHASER_GROUP_CUSTOMER = "01";
export declare const PURCHASER_GROUP_MEMBER = "02";
export declare const PURCHASER_GROUP_SPONSOR = "03";
export declare const PURCHASER_GROUP_STAFF = "04";
export declare const PURCHASER_GROUP_TEL = "05";
export declare const PURCHASER_GROUP_WINDOW = "06";
export declare const CHARGE_MX4D = 1200;
export declare const CHARGE_CVS = 150;
export declare const CHECK_DIGIT_WEIGHTS: number[];
export declare const SORT_TYPES_PAYMENT_NO: number[][];
export declare function publishPaymentNo(cb: (err: Error, no: string | null) => void): void;
export declare function getCheckDigit(source: string): number;
export declare function getCheckDigit2(source: string): number;
export declare function isValidPaymentNo(paymentNo: string): boolean;
export declare function decodePaymentNo(paymentNo: string): string;
