"use strict";
exports.STATUS_UNSENT = 'UNSENT';
exports.STATUS_SENDING = 'SENDING';
exports.STATUS_SENT = 'SENT';
exports.TEMPLATE_COMPLETE = 'COMPLETE';
exports.TEMPLATE_TEMPORARY = 'TEMPORARY';
